POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "100",
  "userName": "Asuha",
  "email": "manu@asuha.dev"
}


###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "200",
  "userName": "Iplayfair",
  "email": "Iplayfair@asuha.dev"
}

###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "300",
  "userName": "Weska",
  "email": "weska@asuha.dev"
}


###
GET http://127.0.0.1:8080/user
Accept: application/json

###
GET http://127.0.0.1:8080/user/200

###
GET http://127.0.0.1:8080/user/500

###
DELETE http://127.0.0.1:8080/user/100

###
DELETE http://127.0.0.1:8080/user/500